# pyproject.toml
[tool.pytest.ini_options]
log_level = "INFO"
log_cli = true
log_cli_level = "INFO"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
addopts = "--durations=0"


