# pyproject.toml
[tool.pytest.ini_options]
log_level = "DEBUG"
log_cli = true
log_cli_level = "DEBUG"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
addopts = "--durations=0"
pythonpath = [
  "python"
]


